<?php
/**
 * @file
 * A generic page to be used during Selenium tests.
 */

/**
 * Implements hook_menu().
 */
function generic_page_menu() {
  $items = array();
  $items['generic_page'] = array(
    'title' => 'Generic Page',
    'description' => 'A generic page for use during Selenium tests.',
    'page callback' => 'drupal_get_form',
    'page arguments' => array('generic_page_form'),
    'type' => MENU_NORMAL_ITEM,
    'access callback' => TRUE,
    'access arguments' => TRUE,
  );
  return $items;
}

/**
 * The generic page form.
 *
 * @param array $form
 *   The Drupal form definition.
 * @param array $form_state
 *   The Drupal form state.
 *
 * @return array
 *   The Drupal form definition.
 */
function generic_page_form(array $form, array &$form_state) {
  $textfield = array(
    '#type' => 'textfield',
    '#title' => 'Text Field',
    '#title_display' => 'invisible',
    '#name' => 'text_field',
  );
  $form = array(
    'generic_page_fieldset' => array(
      '#type' => 'fieldset',
      '#title' => t('Fieldset'),
      '#collapsible' => TRUE,
      '#collapsed' => FALSE,
      'table' => array(
        '#type' => 'tableselect',
        '#header' => array(
          'link' => t('Link'),
          'textfield' => t('Text Field'),
        ),
        '#options' => array(
          'option_1' => array(
            'link' => l(t('Option 1'), 'http://www.google.com'),
            'textfield' => array('data' => $textfield),
          ),
          'option_2' => array(
            'link' => l(t('Option 2'), 'admin'),
            'textfield' => array('data' => array_merge($textfield, array('#default_value' => 'Default Value'))),
          ),
        ),
      ),
    ),
    'checkbox' => array(
      '#type' => 'checkbox',
      '#title' => t('Checkbox'),
    ),
    'radios' => array(
      '#type' => 'radios',
      '#title' => t('Radio Buttons'),
      '#default_value' => 'on',
      '#options' => array(
        'on' => t('On'),
        'off' => t('Off'),
      ),
    ),
    'markup' => array(
      '#markup' => 'Markup',
    ),
  );
  return $form;
}
